# @general settings
[general]
   os = "windows" # os - windows (wsl/wsl2 supported) : linux
   binary = "samp-server.exe" # sa-mp binary files
   config = "server.cfg" # sa-mp config files
   logs = "server_log.txt" # sa-mp log files
   webhooks = "DO_HERE" # discord webhooks
# @compiler settings
[compiler]
   option = ["-Z:+", "-d:2", "-O:2", "LOCALHOST=1"] # compiler options
   includes = ["gamemodes/","pawno/include/", "qawno/include/"] # compiler include path
   input = "gamemodes/bare.pwn" # project input
   output = "gamemodes/bare.amx" # project output
# @dependencies settings
[dependencies]
   github_tokens = "DO_HERE" # github tokens
   root_patterns = ["lib", "log", "root", "amx", "static", "dynamic", "cfg", "config", "json", "msvcrt", "msvcr", "msvcp", "ucrtbase"] # root pattern
   packages = [
      "Y-Less/sscanf?newer",
      "samp-incognito/samp-streamer-plugin?newer"
   ] # package list
